collections:
  - name: "home"
    label: "Página Principal"
    files:
      - label: "Sección Principal"
        name: "hero"
        file: "content/home.json"
        format: "json"
        fields:
          - { label: "Título", name: "titulo-principal", widget: "string" }
          - { label: "Subtítulo", name: "subtitulo", widget: "text" }
          - { label: "Texto Botón", name: "boton", widget: "string" }

